meta_product_name: "Wyder"
meta_title: "Wyder - stop searching, start finding"
meta_description: "High quality and informative video platform for important life decisions"
meta_image: "http://res.cloudinary.com/dvt0t51oq/image/upload/v1591950831/trb3hmwbtu4lyer0ymc1.jpg"
meta_url: "wyder.xyz"
meta_type: "website"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
